# Generated by Django 2.1.3 on 2021-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210618_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accubitsuser',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
